services:
  app:
    build:
      context: nodejs
    container_name: app
    networks:
      - node-network
    volumes: 
      - ./nodejs:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: hereberz/nginx:prod
    container_name: nginx
    networks: 
      - node-network
      - nginx-network
    ports: 
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks:
  node-network:
    driver:  bridge
  nginx-network:
    driver: bridge
